### ISSUE TITLE
Is rq.schedule() not working?

### ISSUE THREAD

**Issue by hveda** [rq/Flask-RQ2#47]
Is rq.schedule(...) not implemented or not working? I try as in doc, but nothing happen. But rq.queue(...) working fine.

```
@rq.job
def add(x, y):
    return x + y

# queue job at a certain datetime (UTC!) from other function.
add.schedule(datetime(2016, 12, 31, 23, 59, 59), 1, 2)
```

**Comment by jezdez** [comment]
@hveda Are you running the scheduler to actually put the job into the queue at the scheduled time? 
Use the [scheduler CLI command](https://flask-rq2.readthedocs.io/en/latest/#commands), which is a wrapper for the [rqscheduler command](https://github.com/rq/rq-scheduler#running-the-scheduler) from rq-scheduler.

**Comment by hveda** [comment]
Yes, so i just use [rqscheduler command](https://github.com/rq/rq-scheduler#running-the-scheduler) to do that?
Am i doing it right?
My worker docker-compose.yml something like:
```
  worker
    build: .
    command: python -m flask rq worker scheduler
    environment:
      - FLASK_APP=serve.py
```
My init file:
```
    rq.init_app(app)
    scheduler = rq.get_scheduler(interval=10)
    scheduler.run()
```

**Comment by hveda** [comment]
I solve the problem as you said but i must run scheduler container itself. Additional docker config i use:
```
scheduler:
    build: .
    command: python -m flask rq scheduler
    environment:
      - FLASK_APP=serve.py
    volumes:
      - .:/var/www/scheduler
```

And access from function:

```
@rq.job
def add(x, y):
    return x + y
# Queue job scheduled
scheduler = rq.get_scheduler(interval=10)
schedule(datetime(2016, 12, 31, 23, 59, 59), add, 1,  2)
```
